---

- name: Configure networks
  template:
    src: templates/ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.name }}
  with_items:
   - "{{ networks }}"
  when: not item.disabled | default(false)
  register: configureNetworkStatus
  notify:
    - restartNetwork

- name: Disable networks
  file:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ item.name }}
    state: absent
  with_items:
   - "{{ networks }}"
  when: item.disabled | default(false)
  register: disableNetworkStatus
  notify:
    - restartNetwork

- name: restart immediately
  service:
    name: network
    state: restarted
  when: configureNetworkStatus.changed or disableNetworkStatus.changed
